spring:
  application:
    name: wedocs
asset:
  folder: assets
  ignore: false
content:
  folder: docs
date:
  format: yyyy-MM-dd
destination:
  folder: dist
img:
  path:
    prepend:
      host: true
    update: false
markdown:
  extensions: HARDWRAPS,AUTOLINKS,FENCED_CODE_BLOCKS,DEFINITIONS
  maxParsingTimeInMillis: 2000
output:
  extension: .html
server:
  port: 8820
template:
  folder: templates
  masterindex:
    file: index.ftl
  page:
    file: page.ftl
  post:
    file: post.ftl
uri:
  noExtension: false
  noExtension.prefix: ''

